import pandas as pd
df=pd.read_csv("./pandas/Datasets/Salary_Data.csv")
print(df.columns)
print(df.shape)
print(df.size)
print(df.head())
print(df.head(2))
print(df.tail())
print(df.tail(8))
print(df.describe())
print(df.info())

df2=pd.read_csv('./pandas/Datasets/Restaurant.csv')
print(df2.head())
print(df2.shape)
print(df2.info())
print(df2.describe())